AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "app/controllers/admin/**/*"
    - "app/dashboards/**/*"
    - "bin/**/*"
    - "tmp/**/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - db/schema.rb
    - Gemfile
    - Guardfile
    - node_modules/**/*
    - Rakefile

inherit_from:
  - config/.rubocop.yml

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines
