scss_files: "app/assets/stylesheets/**/*.scss"

exclude:
  - "app/assets/webpack/**"
  - "app/assets/stylesheets/third-party/**"
  - "client/node_modules/**"

linters:
  ImportantRule:
    enabled: false

  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    enabled: false
